### PR TITLE
added functionalities to add and remove the members in bulk

### PR DESCRIPTION
**Pull request by bountyC0d3r**

### CODE REVIEW

**Review by rakibansary — APPROVED** [review]

**Comment by LieutenantRoger** [comment]
Hi @bountyC0d3r 

The implementation seems reused the original add/remove members method for bulk operations, right ? I think the implementation will work. 

I have two thoughts on the implementation

1.  Is the new endpoint not restricting the member items ?  It might be leads the caller to timeout if the caller passed in a very long list of the member items

2. Since it used the original method for add/delete, so each item will start a neo4j transaction, which might not be efficient and occupy too many neo4j connections.  Maybe can we explore some alternative way to do the bulk in one transaction of neo4j ?   

Thanks

**Comment by bountyC0d3r** [comment]
@LieutenantRoger I agree with you on the 2 points you have mentioned, and here are my thoughts on them:
1. Limit on number of requests we need to put in the `group manager` based on the performance of the API 
2. Yes, we need to implement the bulk add/remove using the single query; which is the target for the next phase, where I'm going to change the query formats to support the v4 of the neo4j db; this will be the part of overall optimisation

**Comment by LieutenantRoger** [comment]
I seems to be able to merge the pull request for this repository, let me know if you need me to do the merge or yourself can do this when you need to merge, thanks

**Comment by bountyC0d3r** [comment]
Merging this with the `develop`

**Pull request merged**
